In [1]:
#Import The Libraries

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [3]:
#Load The Preprocess dataset

In [4]:
dataset = pd.read_csv("dataset_preprocess_ds.csv")
dataset

Crop/Year  Area_Hectares  Production_Tonnes  District_Name_BEED  \
0         2014          32900             8700.0                   0   
1         2014          45300            24200.0                   0   
2         2014         101675            61475.0                   0   
3         2014           4100              900.0                   0   
4         2014           3700             1700.0                   0   
..         ...            ...                ...                 ...   
146       2014          24100             7100.0                   0   
147       2014           1900              800.0                   0   
148       2014           1300                NaN                   0   
149       2014            500              200.0                   0   
150       2014          39800            61475.0                   0   

     District_Name_HINGOLI  District_Name_JALNA  District_Name_LATUR  \
0                        0                    0                    0   
1                        0                    0                    0   
2                        0                    0                    0   
3                        0                    0                    0   
4                        0                    0                    0   
..                     ...                  ...                  ...   
146                      0                    0                    0   
147                      0                    0                    0   
148                      0                    0                    0   
149                      0                    0                    0   
150                      0                    0                    0   

     District_Name_NANDED  District_Name_OSMANABAD  Winter/Summer_Rabi         \
0                       0                        0                          0   
1                       0                        0                          0   
2                       0                        0                          0   
3                       0                        0                          0   
4                       0                        0                          0   
..                    ...                      ...                        ...   
146                     0                        1                          1   
147                     0                        1                          0   
148                     0                        1                          0   
149                     0                        1                          0   
150                     0                        1                          0   

     ...  Rice_Niger seed  Rice_Other  Rabi pulses  Rice_Other Kharif pulses  \
0    ...                0                        0                         0   
1    ...                0                        0                         0   
2    ...                0                        0                         0   
3    ...                0                        0                         0   
4    ...                0                        0                         0   
..   ...              ...                      ...                       ...   
146  ...                0                        0                         0   
147  ...                0                        0                         0   
148  ...                0                        0                         0   
149  ...                0                        0                         0   
150  ...                0                        0                         0   

     Rice_Rice  Rice_Safflower  Rice_Sesamum  Rice_Soyabean  Rice_Sugarcane  \
0            0               0             0              0               0   
1            0               0             0              0               0   
2            0               0             0              0               0   
3            0           

In [5]:
#Drop rows where 'Production_Tonnes' is NAN
dataset=dataset.dropna(subset=['Production_Tonnes'])

In [6]:
indep_X = dataset.drop('Production_Tonnes',axis=1)
dep_Y = dataset['Production_Tonnes']

In [7]:
indep_X

Crop/Year  Area_Hectares  District_Name_BEED  District_Name_HINGOLI  \
0         2014          32900                   0                      0   
1         2014          45300                   0                      0   
2         2014         101675                   0                      0   
3         2014           4100                   0                      0   
4         2014           3700                   0                      0   
..         ...            ...                 ...                    ...   
145       2014          15800                   0                      0   
146       2014          24100                   0                      0   
147       2014           1900                   0                      0   
149       2014            500                   0                      0   
150       2014          39800                   0                      0   

     District_Name_JALNA  District_Name_LATUR  District_Name_NANDED  \
0                      0                    0                     0   
1                      0                    0                     0   
2                      0                    0                     0   
3                      0                    0                     0   
4                      0                    0                     0   
..                   ...                  ...                   ...   
145                    0                    0                     0   
146                    0                    0                     0   
147                    0                    0                     0   
149                    0                    0                     0   
150                    0                    0                     0   

     District_Name_OSMANABAD  Winter/Summer_Rabi         \
0                          0                          0   
1                          0                          0   
2                          0                          0   
3                          0                          0   
4                          0                          0   
..                       ...                        ...   
145                        1                          1   
146                        1                          1   
147                        1                          0   
149                        1                          0   
150                        1                          0   

     Winter/Summer_Summer       ...  Rice_Niger seed  Rice_Other  Rabi pulses  \
0                            0  ...                0                        0   
1                            0  ...                0                        0   
2                            0  ...                0                        0   
3                            0  ...                0                        0   
4                            0  ...                0                        0   
..                         ...  ...              ...                      ...   
145                          0  ...                0                        0   
146                          0  ...                0                        0   
147                          1  ...                0                        0   
149                          1  ...                0                        0   
150                          0  ...                0                        0   

     Rice_Other Kharif pulses  Rice_Rice  Rice_Safflower  Rice_Sesamum  \
0                           0          0               0             0   
1                           0          0               0             0   
2                           0          0               0             0   
3                           0          0               0             0   
4                           0          0               0             0   
..                        ...        ...             ...           ...   
145                         0          

In [8]:
dep_Y

0       8700.0
1      24200.0
2      61475.0
3        900.0
4       1700.0
        ...   
145     4900.0
146     7100.0
147      800.0
149      200.0
150    61475.0
Name: Production_Tonnes, Length: 135, dtype: float64

In [9]:
# Split data and standardize
X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size=0.25, random_state=0)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
# PCA
pca = PCA(n_components=12)
X_train_PCA = pca.fit_transform(X_train_scaled)
X_test_PCA = pca.transform(X_test_scaled)

In [11]:
# Model Evaluation Functions
def r2_prediction(regressor, X_test, y_test):
    y_pred = regressor.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    return r2

# Model Training Functions
def Decision(X_train, y_train, X_test, y_test):
    regressor = DecisionTreeRegressor(random_state=0)
    regressor.fit(X_train, y_train)
    r2 = r2_prediction(regressor, X_test, y_test)
    return r2

def random(X_train, y_train, X_test, y_test):
    regressor = RandomForestRegressor(n_estimators=10, random_state=0)
    regressor.fit(X_train, y_train)
    r2 = r2_prediction(regressor, X_test, y_test)
    return r2

def gradient(X_train, y_train, X_test, y_test):
    regressor = GradientBoostingRegressor(random_state=0)
    regressor.fit(X_train, y_train)
    r2 = r2_prediction(regressor, X_test, y_test)
    return r2

In [13]:
acc_decision = Decision(X_train_PCA, y_train, X_test_PCA, y_test)
acc_random = random(X_train_PCA, y_train, X_test_PCA, y_test)
acc_gradient = gradient(X_train_PCA, y_train, X_test_PCA, y_test)

In [14]:
# Display results
result = pd.DataFrame(index=['n=12'], columns=['DecisionTree', 'RandomForest', 'GradientBoosting'])
result.loc['n=12', 'DecisionTree'] = acc_decision
result.loc['n=12', 'RandomForest'] = acc_random
result.loc['n=12', 'GradientBoosting'] = acc_gradient

In [15]:
print(result)

     DecisionTree RandomForest GradientBoosting
n=12     0.090581     0.297674         0.316385


In [16]:
X_train_PCA.shape

(101, 12)

In [17]:
y_train.shape

(101,)

In [18]:
components = pca.components_

In [19]:
components_df = pd.DataFrame(components, columns=X_train.columns)

In [20]:
components_df

Crop/Year  Area_Hectares  District_Name_BEED  District_Name_HINGOLI  \
0   2.286535e-18      -0.137312            0.043150              -0.096457   
1  -3.527126e-18       0.486006           -0.072731               0.074108   
2   2.295905e-18      -0.348160           -0.031370              -0.320907   
3   1.286971e-17      -0.048638           -0.291815              -0.044476   
4   9.390481e-18       0.011906            0.514012              -0.091369   
5  -7.160632e-18       0.087974            0.342172               0.022116   
6  -8.503111e-18      -0.048186            0.142013              -0.302321   
7   1.550505e-17      -0.247973            0.087070               0.326708   
8   8.897496e-18      -0.062666           -0.095011               0.320837   
9   3.052587e-18      -0.007353            0.017825               0.011750   
10  1.308486e-17      -0.022674           -0.037690               0.124034   
11  5.780448e-18      -0.016548           -0.035370               0.092613   

    District_Name_JALNA  District_Name_LATUR  District_Name_NANDED  \
0             -0.121048             0.037342              0.066524   
1              0.001376             0.058187             -0.071509   
2             -0.146624             0.179884              0.113983   
3             -0.115659             0.400963             -0.218574   
4             -0.208650             0.259928             -0.028777   
5             -0.307413            -0.208955             -0.375832   
6              0.507555             0.041302             -0.439937   
7              0.067038            -0.218925             -0.105733   
8             -0.087100             0.399623             -0.301563   
9             -0.067444            -0.024719              0.026362   
10            -0.041954             0.053447             -0.051790   
11             0.018491             0.066717             -0.026061   

    District_Name_OSMANABAD  Winter/Summer_Rabi         \
0                  0.006527                  -0.354056   
1                  0.003020                   0.213504   
2                  0.100378                   0.442636   
3                  0.229555                  -0.283338   
4                 -0.431357                  -0.073697   
5                  0.463849                   0.062327   
6                 -0.057032                  -0.006314   
7                 -0.074808                  -0.005568   
8                 -0.250128                   0.119274   
9                 -0.005626                  -0.006125   
10                -0.047810                   0.033118   
11                -0.069799                   0.016446   

    Winter/Summer_Summer       ...  Rice_Niger seed  Rice_Other  Rabi pulses  \
0                    0.074596  ...         0.037843                -0.070268   
1                   -0.434901  ...        -0.068016                 0.019615   
2                   -0.150990  ...         0.041666                 0.233885   
3                   -0.254165  ...         0.168336                 0.109700   
4                   -0.167162  ...         0.159459                -0.092060   
5                    0.076889  ...         0.148172                 0.097545   
6                   -0.036357  ...         0.103703                 0.018801   
7                   -0.267769  ...         0.101080                -0.055312   
8                    0.125448  ...        -0.025053                 0.315426   
9                    0.011876  ...        -0.029100                -0.095530   
10                   0.067060  ...        -0.088211                 0.173352   
11                   0.037359  ...        -0.312690                 0.031121   

    Rice_Other Kharif pulses  Rice_Rice  Rice_Safflower  Rice_Sesamum  \
0                   0.028290   0.046953       -0.105828      0.041598   
1                  -0.043413  -0.079117        0.039025     -0.066689   
2                   0.059670   0.046945        0.292399      0.069

In [21]:
top_features_indices = [component.argsort()[-2:][::-1] for component in components]

In [22]:
top_features_indices

[array([27, 10], dtype=int64),
 array([ 1, 27], dtype=int64),
 array([ 8, 24], dtype=int64),
 array([ 5, 22], dtype=int64),
 array([ 2, 23], dtype=int64),
 array([7, 2], dtype=int64),
 array([ 4, 11], dtype=int64),
 array([19, 12], dtype=int64),
 array([18,  5], dtype=int64),
 array([16, 12], dtype=int64),
 array([15, 12], dtype=int64),
 array([28, 13], dtype=int64)]

In [23]:
selected_input_variables = []
for indices in top_features_indices:
    selected_input_variables.append([X_train.columns[i] for i in indices])

In [24]:
print(selected_input_variables)

[['Rice_Sugarcane', 'Winter/Summer_Whole Year '], ['Area_Hectares', 'Rice_Sugarcane'], ['Winter/Summer_Rabi       ', 'Rice_Safflower'], ['District_Name_LATUR', 'Rice_Other Kharif pulses'], ['District_Name_BEED', 'Rice_Rice'], ['District_Name_OSMANABAD', 'District_Name_BEED'], ['District_Name_JALNA', 'Rice_Bajra'], ['Rice_Moong(Green Gram)', 'Rice_Castor seed'], ['Rice_Maize', 'District_Name_LATUR'], ['Rice_Jowar', 'Rice_Castor seed'], ['Rice_Groundnut', 'Rice_Castor seed'], ['Rice_Sunflower', 'Rice_Cotton(lint)']]


In [25]:
from collections import Counter
flattened_features = [feature for sublist in selected_input_variables for feature in sublist]
feature_counts = Counter(flattened_features)
top_features = feature_counts.most_common(5) 
# Change 5 to the desired number of top features
top_feature_names = [feature[0] for feature in top_features]
print(top_feature_names)

['Rice_Castor seed', 'Rice_Sugarcane', 'District_Name_LATUR', 'District_Name_BEED', 'Winter/Summer_Whole Year ']


In [26]:
X_train_selected = X_train[top_feature_names]

In [27]:
X_train_selected

Rice_Castor seed  Rice_Sugarcane  District_Name_LATUR  \
80                  1               0                    1   
68                  0               0                    0   
62                  0               0                    0   
127                 1               0                    0   
144                 0               0                    0   
..                ...             ...                  ...   
12                  0               0                    0   
116                 0               0                    0   
76                  0               0                    0   
132                 0               0                    0   
52                  0               0                    0   

     District_Name_BEED  Winter/Summer_Whole Year   
80                    0                          0  
68                    0                          0  
62                    0                          0  
127                   0                          0  
144                   0                          0  
..                  ...                        ...  
12                    0                          0  
116                   0                          0  
76                    0                          0  
132                   0                          0  
52                    0                          0  

[101 rows x 5 columns]

In [28]:
X_train_selected.shape

(101, 5)

In [29]:
X_test_selected = X_test[top_feature_names]

In [30]:
X_test_selected

Rice_Castor seed  Rice_Sugarcane  District_Name_LATUR  \
135                 0               0                    0   
37                  0               0                    0   
49                  0               0                    0   
141                 0               0                    0   
92                  0               0                    1   
11                  0               0                    0   
58                  0               0                    0   
117                 0               0                    0   
26                  0               0                    0   
128                 0               0                    0   
53                  0               0                    0   
108                 0               0                    0   
28                  0               0                    0   
85                  0               0                    1   
47                  0               0                    0   
100                 0               0                    1   
60                  0               1                    0   
77                  0               1                    0   
146                 0               0                    0   
102                 0               0                    0   
9                   0               0                    0   
30                  0               0                    0   
106                 0               0                    0   
13                  0               0                    0   
69                  0               0                    0   
113                 0               0                    0   
20                  0               0                    0   
2                   0               0                    0   
57                  0               0                    0   
70                  0               0                    0   
95                  0               0                    1   
56                  0               0                    0   
34                  0               0                    0   
129                 0               0                    0   

     District_Name_BEED  Winter/Summer_Whole Year   
135                   0                          0  
37                    1                          0  
49                    0                          0  
141                   0                          0  
92                    0                          0  
11                    0                          0  
58                    0                          0  
117                   0                          0  
26                    1                          0  
128                   0                          0  
53                    0                          0  
108                   0                          0  
28                    1                          0  
85                    0                          0  
47                    0                          0  
100                   0                          0  
60                    0                          1  
77                    0                          1  
146                   0                          0  
102                   0                          0  
9                     0                          0  
30                    1                          0  
106                   0                          0  
13                    0                          0  
69                    0                          0  
113                   0                          0  
20                    1                          0  
2                     0                          0  
57                    0                          0  
70                    0                          0  
95                    0                          0  
56                    0                          0  
34                    1                          0  
129                   0         

In [31]:
y_train.shape

(101,)

In [32]:
from sklearn.model_selection import GridSearchCV

In [47]:
def grid_search_models(X_train_selected, y_train):
    models = ({"RandomForestRegressor": (RandomForestRegressor(), {'criterion': ['squared_error', 'absolute_error'],'max_features': ['sqrt', 'log2'],
            'n_estimators': [10, 100]}),"DecisionTreeRegressor": (DecisionTreeRegressor(), {'criterion': ['squared_error', 'absolute_error'],
            'splitter':['best','random'],'max_features': ['sqrt','log2']}),"GradientBoostingRegressor":(GradientBoostingRegressor(), {'criterion': ['friedman_mse', 'squared_error'],
            'n_estimators':[10,100]})

    results = {}

SyntaxError: '{' was never closed (850760836.py, line 2)